### ISSUE TITLE
login - emails not being received

### ISSUE THREAD

**Issue by SiReid68** [mozilla/thimble.webmaker.org#1142] opened 2015-09-22 09:13 UTC
Hello all,

I'm a teacher with several groups of students using Thimble at the moment. 
Problem for some of them is with logging;
They add their registered school email address and they receive the message telling them an email has been sent with their passkey....except it never arrives.

They have registered with the correct email address, the email isn't in their junk folder either. Problem is for many of them, this is their only email address and therefore cannot log in and access their saved work!
Lots of work being lost at the moment, so any help appreciated.

Simon

**Comment by humphd** [comment] 2015-09-22 13:27
@SiReid68, I'm really sorry to hear this.  Thanks for letting us know.  It sounds like an issue with our Login and/or ID systems.  I'm CC'ing a few people who work on those so they will be aware, and maybe can help offer solutions.

cc @cadecairos, @simonwex, @jbuck, @ashleygwilliams

**Comment by humphd** [comment] 2015-09-22 13:37
@SiReid68, you might also be interested in commenting on #1111, which is about better supporting your use case with students in a classroom setting.  Making Thimble work well for people like yourself is our goal, so it's great to have feedback.

**Comment by cadecairos** [comment] 2015-09-22 13:41
@SiReid68 this is using `thimble.webmaker.org`, and not `thimble.mozilla.org` right? That's why the signup is password-less?

**Comment by cadecairos** [comment] 2015-09-22 13:43
@SiReid68 Okay, I can reproduce the problem on my end. Looks like our system is generating an incorrect welcome email. I'll check it out and file appropriate issues in the components that are acting up. (will reference this issue)

**Comment by cadecairos** [comment] 2015-09-22 13:54
I take that back, it seems to be functioning fine on my end... 

I had forgotten that the first session after account creation doesn't require a login token, but my subsequent logins are working fine.

**Comment by cadecairos** [comment] 2015-09-22 14:05
I'm seeing failures to send emails to the domain "ea.edin.uk.sch". The mailgun API is saying it's not a valid to address.

@SiReid68 Is that the domain your student emails are hosted on?

**Comment by SiReid68** [comment] 2015-09-22 14:05
Thanks for feedback. This is for thimble.webmaker.org

Strangely I am asked for a password after signing in with email, though students are still asked for a passkey.

**Comment by SiReid68** [comment] 2015-09-22 14:05
sggs.org.uk is our domain

**Comment by cadecairos** [comment] 2015-09-22 14:19
@SiReid68 I can't locate any error logs containing that domain.

Perhaps I can offer a couple work-arounds for the time being?

1. When your students are trying to log in, have them try to log in with persona by clicking the blue text to the right of the sign in button:

![screenshot from 2015-09-22 10-13-30](https://cloud.githubusercontent.com/assets/438003/10020766/a77586e8-6112-11e5-8a92-14b9d13a85ac.png)

2. Have them log in from [https://teach.mozilla.org](https://teach.mozilla.org) (the login button is at the top left of the screen. It should prompt them to "migrate" from the one-time-password system to a single password they can create. This option may fail if the emails remain undelivered though.

Please let me know if you have any questions about the above options. I will continue to monitor for issues with undelivered email.

**Comment by cadecairos** [comment] 2015-09-22 14:23
A couple questions so I can get a better picture of your situation:

Are all the students connecting from one computer lab or network?
Are the students using a shared account?

**Comment by SiReid68** [comment] 2015-09-22 19:26
I've emailed you the details to your Mozilla email address, as it has personal details included to try and help resolve this.

Let me know if you don't get it?

thanks

Simon Reid
Head of Computing & E-Learning
Stratford Girls' Grammar School

Telephone: 01789 293759     Ext: 161
Follow us on Twitter: @ShotteryIT


________________________________

**Comment by humphd** [comment] 2015-11-06 19:39
I'm going to close this issue since you two seem to have taken it to email.  If that's wrong, please re-open it.

**Closed by humphd** 2015-11-06 19:39 UTC
Labels: id.webmaker.org, needs attention
