### ISSUE TITLE
Re-think main CTA on homepage.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#1131] opened 2015-09-18 16:29 UTC
Per @LauraReynal's feedback - the Start from Scratch action as the primary CTA isn't inviting enough. Can we come up with a more enticing thing for people to do?

@LauraReynal - what are your thoughts based on what you've seen so far?

**Comment by humphd** [comment] 2015-09-18 20:11
This is a dupe of #1049, let's work there.

**Closed by humphd** 2015-09-18 20:11 UTC
Labels: needs discussion
