### ISSUE TITLE
Investigate ways to help authors to annotate or comment on their projects

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#568] opened 2015-06-16 18:50 UTC
Currently, we've got a couple of methods that authors can use to help or guide people who are looking at their projects: Tutorials & Inline code comments. Each have some problems, which I've gathered from talking with Educators in #557 

**Tutorials**
* Not obvious how to make these
* They clutter up the interface and add cognitive load

**Inline Code Comments**
* They clutter up the code view
* Aren't pretty and can't be styled or formatted
* Each language uses different syntax for commenting

**Possible Alternatives**
* An interface that lets authors add comments on a line or section of code
  * Highlighted lines or sections could have a little :speech_balloon: that could be used to add info
* Make it easy to collapse and expand comments in the code and give them a nicer treatment
* ...

**Features we want**
* A way to focus the reader's attention on a particular line or section
* A sequential progression through a project? Like a walkthrough?
* To be unobtrusive - don't get in the way of the project or editing experience

@cassiemc @Pomax Can you give me some background info about the choices made when designing the current Tutorial feature in Thimble? What were the main goals, features & why?

**Comment by hannahkane** [comment] 2015-06-16 18:56
Wondering if there are any advantages to the Tutorial that we want to retain, even though we know we want to improve the experience. What comes to mind is the "Step 1, Step 2, Step 3" nature of tutorials that might be helpful for true beginners who might find code comments overwhelming.

**Comment by humphd** [comment] 2015-06-16 20:34
I again want to raise my idea of having learning/tutorial content live in the same project filesystem as the content itself.  We have code to render any/all html/css/js already, as well as Markdown (we convert it to html automatically).  As a result, if we have UI to switch between preview mode and learning mode, we can let people develop rich tutorial web pages that travel along with the project itself.

**Comment by hannahkane** [comment] 2015-06-16 21:41
+1 to that idea, which would help with the second bullet point - "clutter up the interface and add cognitive load." We'd still need to address the experience of creating a tutorial, and making that easier / more intuitive.

**Comment by flukeout** [comment] 2015-06-16 23:24
Sounds good - I'll mock up a couple of options, including something like you're describing, @humphd.

**Comment by hannahkane** [comment] 2015-07-08 14:52
This feels like a dupe of #573. @flukeout and @humphd - feel free to re-open if you disagree.

**Closed by hannahkane** 2015-07-08 14:52 UTC
Labels: design, enhancement
