### ISSUE TITLE
Preview Refresh action undoes visual change to Page

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#647] opened 2015-07-02 18:36 UTC
Refresh thimble and open the style.css file

![image](https://cloud.githubusercontent.com/assets/25212/8484798/7c449c2e-20ae-11e5-82b6-37ec38506e85.png)

Change the background color to #ddd, the preview updates accordingly...

![image](https://cloud.githubusercontent.com/assets/25212/8484804/8567fcce-20ae-11e5-9d28-ed5c30616cb6.png)

Press the Refresh arrow in the preview bar, the preview reverts to the previous color...

![image](https://cloud.githubusercontent.com/assets/25212/8484806/89e40d88-20ae-11e5-9a64-6fcad9312323.png)

**Comment by humphd** [comment] 2015-07-02 18:41
This is a dupe of #633, and is going to be fixed by this patch once it lands: https://github.com/humphd/brackets/pull/373

**Closed by humphd** 2015-07-02 18:41 UTC
Labels: bug
