### ISSUE TITLE
allow "download as zip" even when not logged in

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.webmaker.org#1342] opened 2016-01-19 21:06 UTC
Right now visitors need a user account before they can download a project as .zip file, despite there being no real reason to lock downloads behind a login wall. Can we find a way to expose the download option even when a user is not logged in?

**Comment by gideonthomas** [comment] 2016-01-19 21:39
Dupe of https://github.com/mozilla/thimble.webmaker.org/issues/981

**Closed by gideonthomas** 2016-01-19 21:39 UTC
