### ISSUE TITLE
Renaming a project is not counted as a "Update Publish"-able change.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#751] opened 2015-07-29 21:41 UTC
**Steps to reproduce**
* Create a new project and publish it
* Change the project name
* You're not able to update the published version with the new name if that's the only change you made

You should be able to.

**Comment by humphd** [comment] 2015-07-29 21:51
@hannahkane P1 or P2?

**Comment by hannahkane** [comment] 2015-07-29 21:59
Hmm...gonna go with p2. I'd argue it's not essential functionality and there is a workaround. I'm trying to keep p1 as narrow as possible,

**Comment by flukeout** [comment] 2015-07-29 21:59
Agreed.

**Comment by humphd** [comment] 2015-11-13 19:40
Dupe of #719

**Closed by humphd** 2015-11-13 19:40 UTC
Labels: bug, enhancement, P2
