### ISSUE TITLE
Homepage Sign Up & Log In links don't work after Signing Out

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#950] opened 2015-08-27 20:36 UTC
Made a little screencap, after signing out, I'm trying to click them. Are we doing some kind of JS on these? Can we not hardcode their destinations?

![signout](https://cloud.githubusercontent.com/assets/25212/9532458/a384b36c-4cc0-11e5-8dda-a10d1c15473d.gif)

cc @sedge

**Comment by humphd** [comment] 2015-08-27 21:08
I'm seeing:

```
mozillathimblelivepreview.net/bramble/production/dist/main.js:1 Uncaught TypeError: Cannot read property 'fn' of undefined
https://thimble-beta.webmaker.org/homepage/scripts/filesystem/impls/filer/RemoteFiler.js Failed to load resource: the server responded with a status of 404 (Not Found)
/homepage/scripts/main.js:5 Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror
/homepage/scripts/main.js:39 Uncaught TypeError: uuid.v4 is not a function
```

It's possible that the pre-loading of the resources for the editor is messing up the require module for the homepage?

**Comment by humphd** [comment] 2015-08-27 21:20
I'm wondering if those errors are just cache issues, as I can't reproduce now.

**Comment by hannahkane** [comment] 2015-08-27 21:51
I can reproduce consistently, but it always works after I clear the cache. Log in -> sign out -> can't log in -> clear cache - > can log in. Repeat.

**Comment by sedge** [comment] 2015-08-28 02:06
This should be fixed. @hannahkane Can you confirm?

**Comment by hannahkane** [comment] 2015-08-28 04:08
Tested on beta. Here's what's happening now (repeated this entire cycle three times):

Go to homepage
Click Login
Fill out credentials, click Submit
Get a 401 error
Clear cache
Back to homepage
Click Login
Am immediately logged in, without having to re-enter credentials
Log out

(Repeat three times)

**Comment by sedge** [comment] 2015-08-28 15:41
@hannahkane The 401 is really strange. I'd love to se you do that so I can get more information

The auto-login makes sense if the log in to id.webmaker.org succeeded. This is the same mechanism that lets you sign in to services through facebook with a click, as long as you're already signed in to facebook.

**Comment by sedge** [comment] 2015-08-28 15:41
@hannahkane Can you try to reproduce the 401 in an incognito browser session?

**Comment by humphd** [comment] 2015-08-28 15:45
I think this was caching.  None of us can make this fail now.  I'm going to close this, and we should re-file if we see it again.  The homepage was changing so fast yesterday, the cached versions messed up a lot of testing.

**Closed by humphd** 2015-08-28 15:45 UTC
Labels: bug, P1

**Comment by hannahkane** [comment] 2015-08-28 16:09
Tried it again in an incognito browser, just to be sure. Still got an error: http://recordit.co/C57ahLtHQe

**Comment by humphd** [comment] 2015-08-28 16:13
@hannahkane can you load https://thimible-beta.webmaker.org/?a;lwkdjfas;dlkfjasd;lfjk so it gives you a non-cached version and try again?

**Comment by sedge** [comment] 2015-08-28 16:29
@hannahkane Thanks for doing this on PTO. What I really need is to see the error coming back from the server. Here's how you can show me:

First, open the network tab

<img width="318" alt="screen shot 2015-08-28 at 12 22 50 pm" src="https://cloud.githubusercontent.com/assets/1616860/9551517/a4b14218-4d7f-11e5-95da-aa3c12d21e78.png">

Then, follow the STR until you get the 401, then click the 401 request (I couldn't reproduce, so I made up a website to get an error I could click on):

<img width="648" alt="screen shot 2015-08-28 at 12 25 11 pm" src="https://cloud.githubusercontent.com/assets/1616860/9551549/e97b77e2-4d7f-11e5-864b-5e06027fbcf2.png">

Then, make sure the *response headers* are visible and get a screencap or screenshot:

<img width="545" alt="screen shot 2015-08-28 at 12 26 41 pm" src="https://cloud.githubusercontent.com/assets/1616860/9551597/2ca647ae-4d80-11e5-88c9-c68e44cdcaad.png">

Lastly, click on *raw headers*:

<img width="553" alt="screen shot 2015-08-28 at 12 28 16 pm" src="https://cloud.githubusercontent.com/assets/1616860/9551648/5ff67b24-4d80-11e5-832f-08a4c9bd2ebc.png">

And make sure I get a shot of those too:

<img width="551" alt="screen shot 2015-08-28 at 12 28 29 pm" src="https://cloud.githubusercontent.com/assets/1616860/9551652/67bf80d0-4d80-11e5-8e93-5848eace82c3.png">

**Comment by hannahkane** [comment] 2015-08-28 16:36
Apologies if I'm just doing something wrong, and wasting everyone's time.

Screencast - incognito; with the above url: http://recordit.co/MQfRl7ixv7

@sedge - is this what you need?

![screen shot 2015-08-28 at 9 32 38 am](https://cloud.githubusercontent.com/assets/8389648/9551768/f77097dc-4d67-11e5-9a65-407bc16a6364.png)

![screen shot 2015-08-28 at 9 33 51 am](https://cloud.githubusercontent.com/assets/8389648/9551773/fcd3cdf2-4d67-11e5-988e-1f629683c29a.png)

![screen shot 2015-08-28 at 9 32 50 am](https://cloud.githubusercontent.com/assets/8389648/9551770/f8bd4266-4d67-11e5-985e-690f0cad5968.png)

![screen shot 2015-08-28 at 9 33 45 am](https://cloud.githubusercontent.com/assets/8389648/9551771/fac2e7a0-4d67-11e5-94dc-7d7561afd9a5.png)

**Comment by gideonthomas** [comment] 2015-08-28 17:39
@hannahkane I just landed a patch that should fix this. When you get a chance, would you be able to confirm that it works (you might need to clear your cache first).

**Comment by hannahkane** [comment] 2015-08-28 17:42
Can no longer reproduce. Yay!

**Comment by gideonthomas** [comment] 2015-08-28 18:12
Awesome, thanks for testing @hannahkane

**Comment by hannahkane** [comment] 2015-08-28 18:18
Thanks for fixing. :)
