### ISSUE TITLE
There's an .mnt folder in my project

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#788] opened 2015-08-05 18:17 UTC
![image](https://cloud.githubusercontent.com/assets/25212/9093869/7cdd3446-3b63-11e5-947a-8a5b2ef699ec.png)

No idea how it got there!

**Comment by humphd** [comment] 2015-08-05 18:24
This is due to #768 and will be fixed by #756.  The /.mnt dir is a directory of symlinks to actual project folders.  It should be in the root dir `/`, and you shouldn't be mounting `/`, so it's odd that it shows up.

**Comment by humphd** [comment] 2015-08-05 20:01
I am trying to debug this, but can't reproduce.  Can you give more info on what you are doing to make it appear?  The obvious things don't do it for me.

**Comment by humphd** [comment] 2015-08-05 20:26
The fix for this is to transform paths in `bramble.on` events for file operations to use real project paths vs. `.mnt/uuid` prefixes.  The node code is stripping the paths of project roots, and missing the `.mnt/uuid` stuff.  We shouldn't ever send `.mnt/*` paths to the server.  I'll fix tomorrow.

**Comment by humphd** [comment] 2015-08-06 17:03
I think this is fixed now, @flukeout can you confirm and close?

**Comment by humphd** [comment] 2015-08-06 18:47
I'm closing, since we've backed out the symlink stuff.  If this continues in new projects, please re-file.

**Closed by humphd** 2015-08-06 18:47 UTC
Labels: bug, in progress, P1
