### ISSUE TITLE
Clicking on the Publish button gives no feedback

### ISSUE THREAD

**Issue by k88hudson** [mozilla/thimble.webmaker.org#860] opened 2015-08-14 21:05 UTC
When not logged in, if I click the "Publish" button, nothing seems to happen (I think the Publish button might be fading in and out), and this error pops up in the Console:

```
Uncaught TypeError: Cannot read property 'remove' of null       bramble-popupmenu.js:39
```

This is on latest Chrome

**Comment by sedge** [comment] 2015-08-17 16:32
This is a duplicate of https://github.com/mozilla/thimble.webmaker.org/issues/512. Closing

**Closed by sedge** 2015-08-17 16:32 UTC
Labels: P1, QA
