### ISSUE TITLE
When I navigate from tutorial.html to css.styles the preview window should change

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/thimble.webmaker.org#1177] opened 2015-10-10 14:16 UTC
Currently if I am working on a tutorial and then click back on the css.style sheet the tutorial stays in the preview window.

It isn't much but it would save a click and some user confusion if the window goes back to the DOM preview when you click on css.style.

**Comment by humphd** [comment] 2015-10-10 14:58
So you have the `tutorial.html` file open in the editor, and you *are* or *are not* in `Tutorial` mode?  And you click on the `style.css` file and the preview stays on `tutorial.html`?  And you expect what to happen, that isn't happening?

Thanks for filing, just trying to understand the issue so I can reproduce here.

**Comment by jgmac1106** [comment] 2015-10-10 15:19
Yes Here is a quick screenshot
![Navigation](https://cloud.githubusercontent.com/assets/10534566/10411825/9f42f4c4-6f40-11e5-8eb7-04ccc1cff2c0.gif)
k screenshot

**Comment by jgmac1106** [comment] 2015-10-11 10:54
What would be the best case scenario IMO if someone clicked on the tutorial file or tutorial tab the preview window would automatically expand over to the file tray and the editor would be hidden. 

Thus learners would have the full tutorial and see the tutorial mark up unless they manually resized the window.

I keep seeing students edit the tutorial mark up when they meant to edit the index.html markup.

Not sure if that is possible but it would be neat.

**Comment by flukeout** [comment] 2015-11-12 18:46
Interesting - I'm not reaaaaly sure I'm following all of this other than a take-away that the tutorial feature is confusing, which I agree with.

I'll start a new issue where we can catalogue some of the problems and come up with some new ideas.

**Comment by hannahkane** [comment] 2015-11-18 19:19
Is this all covered in #1246? Should we close?

**Comment by gideonthomas** [comment] 2016-01-06 21:33
Closing since the discussion has been picked up here: https://github.com/mozilla/thimble.webmaker.org/issues/1246

**Closed by gideonthomas** 2016-01-06 21:33 UTC
