### ISSUE TITLE
Choose dark theme & customize current themes

### ISSUE THREAD

**Issue by JordanTheriault** [mozilla/thimble.webmaker.org#606] opened 2015-06-24 18:36 UTC
The current dark theme is a placeholder and needs to be replaced. Further, these themes will need to be customized in the theme's .less files located in `humph/brackets/bramble` to better fit the UI look and feel.

**Comment by humphd** [comment] 2015-07-22 17:26
Dupe of #576.

**Closed by humphd** 2015-07-22 17:26 UTC
Labels: UX
