### ISSUE TITLE
Localize new Thimble UI

### ISSUE THREAD

**Issue by Arty-chan** [mozilla/thimble.webmaker.org#475] opened 2015-03-17 17:10 UTC
not an issue from the general webmaker.org site, but definitely in thimble.webmaker.org, not sure about other tools.

Tested using French and Dutch localization with a project from scratch at thimble.webmaker.org
* "Join Webmaker" button is in English
* "Login" button is in French, however, if you click on it, you get the login pop-up window in English
* Functionality itself has no problems
* After logging in, the dropdown from username ("My makes", "My profile" etc.) is in English

**Comment by Pomax** [comment] 2015-03-18 19:21
cc @alicoding

**Comment by alicoding** [comment] 2015-03-18 19:26
Not just missing strings there but the entire login and signup flow for thimble doesn't seem to be localized at all. We're probably didn't include the JSON file necessary to display the strings in that language. (Based on what I see on the production site).

**Comment by alicoding** [comment] 2015-03-18 19:31
At least I can confirm that "Join Webmaker" is not in any JSON file at all. I'm checking other stuff right now to see what else is not incluced or what is wrong there.

**Comment by humphd** [comment] 2015-07-22 14:55
I'm going to morph this into a general l10n ticket for new Thimble UI.  None of it is localized at the moment, and it needs to be.

**Comment by humphd** [comment] 2015-07-22 14:56
Also note: doing this also requires some work in Brackets...there are bugs filed in https://github.com/humphd/brackets/milestones/Thimble%20MVP.

**Comment by hannahkane** [comment] 2015-07-22 21:03
Can we clarify the outcome of this ticket needed for MVP - is it resolving the relevant Brackets tickets + getting the strings into Transifex?

**Comment by hannahkane** [comment] 2015-07-24 19:05
Moving this to p3, because it's not a blocker for launch. Would still be good to get clarity on what the necessary work is.

**Comment by hannahkane** [comment] 2015-09-08 17:39
@humphd - I'm wanting to move this to a P1 now. Have received several requests. Can you help clarify what the specific tasks are to make l10n happen?

**Comment by humphd** [comment] 2015-09-08 18:05
I'll get @alicoding to also add what he knows, but here's my sense of the work:

* audit our Thimble routes to make sure they are all l10n aware (i.e., stripping locale/lang info from the request or headers).  I think we are in pretty good shape for this.
* extract all strings from the Thimble front-end web app, and have them get written via nunjucks template substitutions.  Also make sure we don't have any strings that are being injected dynamically in the front-end code--I'm sure we have some.  We should aim to move these to the server if possible.
* Do the same process for Bramble.  There aren't a lot of things new strings in Bramble vs. Brackets, but there are some (e.g., selfie taker).  Brackets currently has translations for these locales: https://github.com/adobe/brackets/tree/master/src/nls
* Connect the locale loading code in Bramble and Thimble.  I *think* we have most of this done already, but I need to confirm.
* Localize any extensions we use in Brackets that use strings.
* Get all the strings listed above into Transifex, and get them localized
* Get our deployment/build stuff to automatically download and use the locales we have from Transifex.

The good news is that none of this is super hard, and we've done it all before.  The bad news is that there's a bunch of it.  I would guess that there's 2 weeks of work here for multiple people, maybe more.

**Comment by alicoding** [comment] 2015-09-09 18:50
Since we are using nunjucks so a lot of work here might be easier, but might have some old technical debt bugs that may or may not cause any problem for Thimble app (I suspect that we will be okay)
1. Home page: https://thimble.mozilla.org/
It looks like we are using nunjuck here, so doing localization for this page shouldn't be too hard at all. We simply need to replace any hardcoded string from here https://github.com/mozilla/thimble.webmaker.org/blob/bramble/views/homepage/index.html and use `gettext()` for that

2. We need to make sure we only enable language that fully translated 100% since there are bunch of them right now that is not translated but you can still access them.

3. For bramble/bracket part this part we need to implement it the way @humphd mentioned above since they are using requirejs l10n which might require some extra work in term of sharing resources / write script to convert them the way Transifex expects them (I don't recall the format for requirejs l10n, but I suspect we need some extra work here)


I honestly don't know if it is worth it or a good idea to automate the process of getting the locale from/to Transifex since it is only a single project and I believe that if we document the process and do it manually every week or two at least we can monitor / QA the quality of the translation here as well.

**Comment by simonwex** [comment] 2015-10-21 21:55
Hey @humphd, picking this back up. How much of this can you (CDOT) help with this and how many folk  from my team would you need in order to get this done? – I'm assuming that it's three people X three weeks.

**Comment by simonwex** [comment] 2016-01-26 20:01
Closing as we're continuing work on this in separate issues.
See #1318 for work.

**Closed by simonwex** 2016-01-26 20:01 UTC
Labels: Localization, P1
