### ISSUE TITLE
Ugly AWS 404 when publishing without index.html

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/thimble.webmaker.org#1090] opened 2015-09-10 20:11 UTC
If you delete `index.html`, you get a 404, but it's an ugly, AWS one with a guru meditation or something.

Would love to see a stylized 404 a là github.

**Comment by secretrobotron** [comment] 2015-09-10 20:12
e.g. http://bramble-staging.s3-website-us-east-1.amazonaws.com/cepheid/303

**Comment by secretrobotron** [comment] 2015-09-10 20:12
And maybe the 404 can detect if you're signed in and looking at something you published, and say "are you seeing this page because you deleted your index.html?"

**Comment by flukeout** [comment] 2015-09-10 20:45
Good catch. Some other ideas:
* Showing a list of HTML files that the user can pick from that are part of the project
* Straight-up redirecting to one of the HTML pages

We've already built a 404 page, but I guess it's not always showing up when it should.

**Comment by gideonthomas** [comment] 2015-09-10 20:46
Cannot reproduce on prod (I see the real 404 page that @flukeout designed) but I see this on staging

**Comment by secretrobotron** [comment] 2015-09-10 21:15
Oh! Maybe it's just missing on staging. (should be there too probably, no?)

**Comment by gideonthomas** [comment] 2015-09-10 21:24
Hmm, yeah that's an interesting question, on the 404 page we have links (hard-coded) that reference production (for e.g. the remix links) so I wonder what we should do about that slash if it might just be better or easier to show the ugly AWS 404 page on staging
cc @jbuck

**Comment by humphd** [comment] 2015-11-13 20:04
Dupe of #1203

**Closed by humphd** 2015-11-13 20:04 UTC
Labels: enhancement
