### ISSUE TITLE
Staging: Editor not loading again (same error as before)

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#896] opened 2015-08-19 22:21 UTC
Got myself into this state after trying to load the editor...

![image](https://cloud.githubusercontent.com/assets/25212/9370519/c3003b76-4685-11e5-88a3-d6bb104a4a90.png)

This is the ```Uncaught TypeError: Cannot read property 'doc' of undefined``` we've seen before.

I'm able to resolve it by clearing my bramble cookies...

![image](https://cloud.githubusercontent.com/assets/25212/9370538/f9a85794-4685-11e5-880b-976665080eab.png)

Anyway - worried this is a bigger problem that users might run into at some point too.

**Comment by flukeout** [comment] 2015-08-19 22:22
I had no other tabs with thimble open.

**Comment by humphd** [comment] 2015-08-20 01:51
Can you please paste a full stack trace in this bug?  I can only see the top frame, and I'd love to see it all.

**Comment by humphd** [comment] 2015-08-24 15:06
I was able to hit this today.  I haven't been using the app a lot for a week, while on holidays.  I came back this morning, and the app was down (in https://github.com/MozillaFoundation/mofo-devops/issues/155 we have determined that our Heroku tier was sleeping the node app when inactive, and forcing it to start again).  After it restarted I went to an old project.  It tried to load, and eventually did the same thing as @flukeout reported above.  I did a bit more digging and confirmed that the filesystem is OK, and that the expected project files are in fact there.  I suspect this is the session getting corrupted/expiring.

![screenshot 2015-08-24 11 03 03](https://cloud.githubusercontent.com/assets/427398/9443634/173f4cea-4a50-11e5-94bb-f7433ac45a5f.png)

**Comment by humphd** [comment] 2015-08-24 15:42
We figured this out.  The issue is caused by setting the preview mode to "mobile" and when it loads it tries to change the preview mode and reload the iframe browser, which isn't set up yet.  It's a timing bug, and can be fixed by just avoiding the reload if the browser isn't ready yet.  I'll do a patch.

**Comment by humphd** [comment] 2015-08-24 17:32
Fixed!

**Closed by humphd** 2015-08-24 17:32 UTC
Labels: attention needed, bug, critical, P1, QA
