### ISSUE TITLE
Tutorial.html file reappears when working with Tutorial.md

### ISSUE THREAD

**Issue by emmairwin** [mozilla/thimble.webmaker.org#1191] opened 2015-10-22 04:15 UTC
Perhaps I am going about this the wrong way but here are my steps.

1) Add tutorial file  (creates tutorial.html)
2) Rename tutorial file to tutorial.md
3) editing tutorial.md edits are reflected correctly for a brief edit or two ( not sure exact scenerio)
4) tutorial.html reappears and updates to tutorial.md stop updating.   

So tutorial.md works, but I need to keep deleting tutorial.html as I go.

**Comment by humphd** [comment] 2015-10-22 14:49
This is by design.  How it works is that every time a Markdown file is saved, it will also produce an associated HTML file.  Here's an example:

![screen shot 2015-10-22 at 10 44 34 am](https://cloud.githubusercontent.com/assets/427398/10668404/275018f2-78aa-11e5-8562-eac9ae6c29be.png)

Here I've created a simple `tutorial.md` file.  It has automatically created `tutorial.html` as well:

![screen shot 2015-10-22 at 10 44 43 am](https://cloud.githubusercontent.com/assets/427398/10668421/38e704ae-78aa-11e5-9399-4c6a8b819142.png)

You'll note that the `tutorial.html` file has a large comment block at the top indicating that this file is generated from `tutorial.md`.

The fact that the changes to the `tutorial.md` file don't automatically show-up in the `tutorial.html` file's preview *might* be the same bug @flukeout filed in https://github.com/mozilla/thimble.webmaker.org/issues/1174.  If you refresh the preview, it will pick up the new changes.

I'm going to close this, but feel free to re-open it if you think there's a bug I can fix.  I'll also leave a comment in that other bug about md->html not auto-updating on save in the preview.

**Closed by humphd** 2015-10-22 14:49 UTC

**Comment by emmairwin** [comment] 2015-10-22 15:10
@humphd I will try again, what I experienced was my changes stopped updating in the tutorial file view.  But knowing this might change things.
I don't read large comment blocks I guess ;)
